### ISSUE TITLE
make use of OpenGL direct state access

### ISSUE THREAD

**Issue by liquid600pgm** [liquid600pgm/rapid#4]
It leads to much less buggy code and less headaches trying to debug what went wrong in the state machine.

**Comment by liquid600pgm** [comment]
Turns out it's not very well documented, replaced this with a `withX` template like in the first version of rapid

**Comment by RSDuck** [comment]
sorry for hijacking this issue, but DSA is still required, though it's only used in very few places. Unfortunately my machine only supports up to OGL 4.0, which makes the library not useable for me. 

That's why I ask if the dependency can't be removed entirely? With webgl support it probably has to be done any way since afaik it doesn't support it.

**Comment by liquid600pgm** [comment]
I don't require OpenGL 4.0+, only the ARB_direct_state_access extension. I can remove it, but it will make the engine's source code quite unreadable I'm afraid. I'll look into that though.
