### ISSUE TITLE
Is there any plan to get it working on mobile devices?

### ISSUE THREAD

**Issue by mrhdias** [liquid600pgm/rapid#5]
Hi, Is there any plan to get it working on mobile devices (android/iOS)?
Is it a difficult task to integrate with this project? https://github.com/iffy/wiish

**Comment by liquid600pgm** [comment]
I plan to support as many platforms as possible, however mobile is not on the roadmap yet.
Currently I'm going to be working on a WebGL backend, which should make creating mobile games possible in at least *some* way.
I don't think mobile support will be possible until I switch to SDL2 from GLFW, but I don't know if that will ever happen (I'm happy with my current library choice, and SDL2 not very easy to wrap using nimterop).

**Comment by liquid600pgm** [comment]
After thinking through this for a while, I'll say that no. rapid isn't going to support mobile, as my main focus is desktop games. 

Nim currently doesn't really have good tooling for exporting to Android and iOS, which makes it way more difficult to make mobile apps---you have to use Java and JNI to bind the code to Android, and that's rather cumbersome. I also don't have a way of testing iOS, since that requires macOS afaik.
