### ISSUE TITLE
rapid/audio doesn't compile on windows

### ISSUE THREAD

**Issue by liquid600pgm** [liquid600pgm/rapid#8]
There are a ton of undefined reference to `__imp_soundio_*` link errors when compiling on Windows.

Note that this only happens on MinGW—gcc on Linux works just fine.

### Reproducing
```
$ nim c --passL:-lole32 -r tests/taudio
```

**Comment by teimoso** [comment]
I don't know of what significance this might be, since I made some strange compromises, but I am able to get `taudio.nim` to compile with a MinGW-w64 toolchain using the following command:
```
nim c --threads:on taudio.nim
```
(so I guess nothing special).
It, however, crashes shortly after running ("taudio.exe has stopped working"), with or without `--passL:-lole32`. Other tests seem to run fine.

Normally, I use [MSYS2](https://www.msys2.org/) on Windows, but its shell was causing complications with nimterop (probably related to https://github.com/nimterop/nimterop/issues/126), so I had to place its binary directories in my Windows PATH and compile from a regular command prompt.

I tried downloading the rapid git repository and compiling from there, but I encountered link errors with undefined references to `_glfw[...]`. I noticed during compilation that pulled git repositories were going to the directory I downloaded instead of `.nimble\pkgs\rapid-0.1.0`; maybe that has something to do with it? In any case, copying the `tests` files to a different directory stopped those errors.


##### Nim compiler version
```
0.20.99 [Windows: amd64]
Compiled at 2019-09-05
```
(sorry; haven't installed 1.0...)

**Comment by liquid600pgm** [comment]
@teimoso I fixed it in a recent commit, so it compilex fine, However, it doesn't run very well (crashes with a SIGSEGV) but that's a cross-platform issue.

**Comment by teimoso** [comment]
oh. I guess on the bright side I was finally able to get any rapid examples to compile whatsoever.

**Comment by liquid600pgm** [comment]
It's strange that twindow doesn't compile, can you open an issue for that?

**Comment by teimoso** [comment]
`twindow.nim` does compile for me. Did I make a mistake somewhere in one of my comments?

**Comment by liquid600pgm** [comment]
@teimoso my bad, I wasn't home so I didn't really think before typing.
